# Generated by Django 5.1.3 on 2024-11-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_remove_course_description_remove_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='groups', through='users.GroupStudent', to='users.student'),
        ),
    ]
